from __future__ import annotations

import subprocess
import shutil
from dataclasses import dataclass, field
from pathlib import Path
from typing import List

from core.config import get_settings
from core.logger import get_logger

logger = get_logger(__name__)


class DwgIngestError(RuntimeError):
    pass


@dataclass
class DwgIngestResult:
    source_file: Path
    dxf_path: Path | None = None
    rendered_images: List[Path] = field(default_factory=list)
    conversion_logs: List[str] = field(default_factory=list)


def validate_cad_file(file_path: Path) -> None:
    settings = get_settings()
    if file_path.suffix.lower() not in {".dwg", ".dxf"}:
        raise DwgIngestError("Unsupported CAD format. Upload .dwg or .dxf.")
    if file_path.stat().st_size > settings.max_upload_size_mb * 1024 * 1024:
        raise DwgIngestError(f"CAD file too large. Max allowed is {settings.max_upload_size_mb}MB.")


def _run_converter(input_path: Path, output_dir: Path) -> tuple[Path | None, List[str]]:
    settings = get_settings()
    converter = _resolve_converter_path(settings.dwg_converter_path.strip())
    logs: List[str] = []
    if not converter:
        logs.append("CAD conversion failed: DWG converter not found. Set DWG_CONVERTER_PATH to ODAFileConverter.exe.")
        return None, logs
    if not Path(converter).exists():
        logs.append(f"CAD conversion failed: DWG converter not found at {converter}.")
        return None, logs

    output_dir.mkdir(parents=True, exist_ok=True)
    source_dir = output_dir / "_source"
    source_dir.mkdir(parents=True, exist_ok=True)
    isolated_input = source_dir / input_path.name
    shutil.copy2(input_path, isolated_input)

    cmd = [
        converter,
        str(source_dir),
        str(output_dir),
        "ACAD2018",
        "DXF",
        "0",
        "1",
    ]
    for attempt in range(1, 3):
        try:
            proc = subprocess.run(
                cmd,
                check=False,
                capture_output=True,
                text=True,
                timeout=settings.dwg_conversion_timeout_sec,
            )
            logs.append((proc.stdout or "").strip())
            logs.append((proc.stderr or "").strip())
            if proc.returncode not in (0, 1):
                logs.append(f"CAD conversion failed: converter exit code {proc.returncode} (attempt {attempt}).")
        except subprocess.TimeoutExpired:
            logs.append("CAD conversion failed: conversion timed out.")
            return None, logs
        except Exception as exc:  # pragma: no cover
            logs.append(f"CAD conversion failed: {exc}")
            return None, logs

        generated = list(output_dir.rglob(f"{input_path.stem}.dxf"))
        if generated:
            return generated[0], logs

    logs.append("CAD conversion failed: DXF output not generated by converter.")
    return None, logs


def _resolve_converter_path(configured: str) -> str:
    if configured:
        return configured
    path_cmd = shutil.which("ODAFileConverter.exe") or shutil.which("ODAFileConverter") or shutil.which("odafc")
    if path_cmd:
        return path_cmd
    common = [
        r"C:\Program Files\ODA\ODAFileConverter\ODAFileConverter.exe",
        r"C:\Program Files\ODA\ODAFileConverter 25.12.0\ODAFileConverter.exe",
        r"C:\Program Files (x86)\ODA\ODAFileConverter\ODAFileConverter.exe",
    ]
    for path in common:
        if Path(path).exists():
            return path
    return ""


def ingest_dwg(file_path: Path, analysis_id: str) -> DwgIngestResult:
    validate_cad_file(file_path)
    settings = get_settings()
    result = DwgIngestResult(source_file=file_path)
    if file_path.suffix.lower() == ".dxf":
        result.dxf_path = file_path
        return result

    temp_dir = settings.dwg_temp_dir / analysis_id
    converted, logs = _convert_with_ezdxf_odafc(file_path, temp_dir)
    if converted is None:
        converted, cli_logs = _run_converter(file_path, temp_dir)
        logs.extend(cli_logs)
    result.conversion_logs.extend([line for line in logs if line])
    result.dxf_path = converted
    if converted:
        result.rendered_images = render_dxf_images(converted, analysis_id)
    return result


def _convert_with_ezdxf_odafc(input_path: Path, output_dir: Path) -> tuple[Path | None, List[str]]:
    logs: List[str] = []
    try:
        import ezdxf  # type: ignore
        from ezdxf.addons import odafc  # type: ignore

        output_dir.mkdir(parents=True, exist_ok=True)
        out_dxf = output_dir / f"{input_path.stem}.dxf"
        converter = _resolve_converter_path(get_settings().dwg_converter_path.strip())
        if converter:
            try:
                ezdxf.options.set("odafc-addon", "win_exec_path", converter)
            except Exception:
                pass
        odafc.convert(str(input_path), str(out_dxf), version="R2018", audit=True, replace=True)
        if out_dxf.exists():
            # validate readable by ezdxf before using
            ezdxf.readfile(str(out_dxf))
            logs.append("DWG converted by ezdxf.odafc.")
            return out_dxf, logs
        logs.append("ezdxf.odafc conversion did not produce DXF.")
        return None, logs
    except Exception as exc:
        logs.append(f"ezdxf.odafc conversion failed: {exc}")
        return None, logs


def render_dxf_images(dxf_path: Path, analysis_id: str) -> List[Path]:
    settings = get_settings()
    target_dir = settings.dwg_temp_dir / analysis_id / "renders"
    target_dir.mkdir(parents=True, exist_ok=True)
    output_png = target_dir / f"{dxf_path.stem}_plan.png"
    try:
        import ezdxf  # type: ignore
        import matplotlib.pyplot as plt  # type: ignore
        from ezdxf.addons.drawing import Frontend, RenderContext  # type: ignore
        from ezdxf.addons.drawing.config import Configuration  # type: ignore
        from ezdxf.addons.drawing.matplotlib import MatplotlibBackend  # type: ignore

        doc = ezdxf.readfile(str(dxf_path))
        render_dpi = max(96, int(settings.cad_render_dpi))
        fig = plt.figure(figsize=(18, 14), dpi=render_dpi)
        ax = fig.add_axes([0, 0, 1, 1])
        ax.set_axis_off()
        ctx = RenderContext(doc)
        out = MatplotlibBackend(ax)
        frontend = Frontend(ctx, out, config=Configuration(lineweight_scaling=0.5))
        frontend.draw_layout(doc.modelspace(), finalize=True)
        fig.savefig(output_png, dpi=render_dpi, bbox_inches="tight", pad_inches=0)
        plt.close(fig)
        return [output_png]
    except Exception as exc:  # pragma: no cover
        logger.warning("DXF render fallback unavailable for %s: %s", dxf_path.name, exc)
        return []


def cleanup_dwg_temp(analysis_id: str) -> None:
    settings = get_settings()
    temp_dir = settings.dwg_temp_dir / analysis_id
    if temp_dir.exists():
        shutil.rmtree(temp_dir, ignore_errors=True)
